Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace IOU.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IOU.Models;
using Microsoft.AspNetCore.Http;

namespace IOU.Pages
{
    public class IndexModel : PageModel
    {

        private readonly ILogger<IndexModel> _logger;
        private readonly IOU.Data.IOUContext _context;

        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public string Password { get; set; }

        public string Msg { get; set; }

        [BindProperty]
        public Models.User user { get; set; }


        public IndexModel(ILogger<IndexModel> logger,
            IOU.Data.IOUContext context)
        {
            _logger = logger;
            _context = context;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            

            if (_context.User.SingleOrDefault(u => u.userName == Username && u.password == Password) != null)
            {
                user = _context.User.Single(user1 => user1.userName == Username);
                HttpContext.Session.SetString("username", user.userName);
                HttpContext.Session.SetString("user-type", user.userType.ToString());

                _logger.LogInformation("Found user of type {0}", user.userType.ToString());

                if (HttpContext.Session.GetString("user-type") == "admin")
                {
                    return RedirectToPage("./Admin/Index");
                }
                else if ((HttpContext.Session.GetString("user-type") == "user"))
                {
                    return RedirectToPage("./User/Index");
                }
                else
                {
                    return RedirectToPage("./Index");
                }

            }
            else
            {
                Msg = "Invalid";
                return Page();
            }
        }

        
    }
}

Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IOU.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace IOU.Pages
{
    public class LoginModel : PageModel
    {
        private readonly ILogger<LoginModel> _logger;
        private readonly IOU.Data.IOUContext _context;

        public string Username { get; set; }
        public string Password { get; set; }

        public string Message { get; set; }

        public Models.User User { get; set; }

        public LoginModel(ILogger<LoginModel> logger,
            IOU.Data.IOUContext context)
        {
            _logger = logger;
            _context = context;
        }

        public void OnGet()
        {

            _logger.LogInformation("we are in the Login page");
            //return Page();

        }

        public IActionResult OnPost()
        {
            if (Username.Equals("abc") && Password.Equals("123"))
            {
                HttpContext.Session.SetString("username", Username);
                return RedirectToPage("./Privacy");
            }
            else
            {
                Message = "Invalid Username or Password";
                return Page();
            }



        }

    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IOU.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Welcome.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IOU.Pages
{
    public class WelcomeModel : PageModel
    {
        public string Username { get; set; }

        public void OnGet()
        {
            Username = HttpContext.Session.GetString("username");
            //Page();
        }

        public IActionResult OnGetLogout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToPage("Index");
        }        
        
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

<h3>Login Form</h3>
@Model.Msg
<form method="post" asp-page="Index">
    <table>
        <tr>
            <td>Username</td>
            <td><input type="text" asp-for="@Model.Username" /></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><input type="password" asp-for="@Model.Password" /></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Login" /></td>
        </tr>
    </table>
</form>
</body>
</html>

Pages/Login.cshtml
@page
@model IOU.Pages.LoginModel
@{
}

<h1>Login</h1>

<p>this is the login page</p>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

<h3>Login Form</h3>
@Model.Message
<form method="post" asp-page="Index">
    <table>
        <tr>
            <td>Username</td>
            <td><input type="text" asp-for="@Model.Username" /></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><input type="password" asp-for="@Model.Password" /></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Login" /></td>
        </tr>
    </table>
</form>
</body>
</html>

Pages/Welcome.cshtml
@page
@model IOU.Pages.WelcomeModel
@{
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Welcome</title>
</head>
<body>

<h1>Welcome @Model.Username</h1>
<a asp-page="Welcome" asp-page-handler="Logout">Logout</a>

</body>
</html>